#!/usr/bin/env python3
import numpy as np
import math
import time
from scipy.stats import planck
import simpy

RESISTENCIA= 60e6
TIEMPO_TOTAL_SIMULACION=1.0
#LAMBDA_EXCITATORIO=9655.0
LAMBDA_EXCITATORIO=2000.0
LAMBDA_INHIBITORIO=434.0
TASA_DE_ARRIBO_EXCITATORIO=(1/LAMBDA_EXCITATORIO)
TASA_DE_ARRIBO_INHIBITORIO=(1/LAMBDA_INHIBITORIO)
PASO=1e-6
#ALFA_MAX=50e-9
CAPACITANCIA_MEMBRANA=250e-12
#TAU_ALFA=1e-3
TAU_MEMBRANA=(RESISTENCIA*CAPACITANCIA_MEMBRANA)
CORRIENTE_NULA=0
ALFA_EXCITATORIO=390.5e-12
TAU_EXCITATORIO=0.2e-3
TAU_INHIBITORIO=2e-3
ALFA_INHIBITORIO= -74e-12
POTENCIAL_DE_REPOSO=-60e-3
TENSION_UMBRAL=-50e-3
TIEMPO_REFRACTARIO=2e-3
